trigger:
  branches:
    include:
      - '*'

variables:
  deployment: ''
  version: ''
  patchWildcardPath: ''
  majorWildcardPath: ''
  minorWildcardPath: ''
  cdnPath: ''
  branch: ''

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  ## Only on the `main` branch, check if the last commit comes from semantic-release-bot
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - bash: |
          first_line=$(git log -1 --pretty=%s)
          echo $first_line
          if [[ $first_line == "chore(release/components):"* ]]; then
            echo "The last commit is a version bump => code will be deployed."
            echo "##vso[task.setvariable variable=deployment]code"
          elif [[ $first_line == "docs:"* ]]; then
            echo "The last commit is a docs change only => only storybook will be deployed."
            echo "##vso[task.setvariable variable=deployment]docs"
          else
            echo "The last commit is neither a version bump nor a docs change only => code will not be deployed."
            echo "##vso[task.setvariable variable=deployment]none"
          fi
        displayName: 'Set deployment type'
      - bash: |
          echo "$(deployment)"
        displayName: 'Log deployment type'

  - script: |
      if [[ $(deployment) != "none" ]]; then
        npm i pnpm@8.6.2 -g
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true pnpm i
        cd packages/components && pnpm run build.cdn
      else
        echo "Deployment type is 'none', therefore no build needed."
      fi
    displayName: 'Install dependencies and build'

  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      ## If the branch is not 'main' then normalize the branch name (remove 'refs/heads/' and replace '/' with '_') and set the [branch] variable to the normalized
      ## branch name to use the branch name as folder path in the CDN
      - bash: |
          set -x
          REF=$(Build.SourceBranch)
          echo $REF
          REG='[a-z]*/[a-z]*/([0-9a-zA-Z/-]*)'
          if [[ $REF =~ $REG ]]; then echo found; fi
          branch=${BASH_REMATCH[1]////_}
          echo $branch
          # IMPORTANT: We have to stop "set -x" here to prevent accidental apostrophes in the branch name
          # https://github.com/microsoft/azure-pipelines-tasks/issues/10331#issuecomment-1423932651
          set +x
          echo "##vso[task.setvariable variable=branch]$branch"
        displayName: 'Normalize branch name (remove refs/heads/ and replace / with _)'
      - bash: |
          echo "$(branch)"
        displayName: 'Log normalized branch name'
      ## Push to CDN feature branch folder
      - template: templates/push-to-storage-feature.template.yml
      ## Purge CDN for branch folder
      - template: purge-feature-cdn.template.yml

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      ## Push to CDN version folders
      - template: templates/push-to-storage-main.template.yml
      ## Purge CDN for all version folders
      - template: purge-main-cdn.template.yml

      ## If deployment variable is set to 'none' do nothing
      - script: |
          if [[ $(deployment) == "code" ]]; then
            echo "Everything has been deployed."
          elif [[ $(deployment) == "docs" ]]; then
            echo "Only storybook has been deployed."
          else
            echo "Nothing has been deployed."
          fi
        displayName: 'Deployment status'
