packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**/!(dist)/**'
  - 'demos/**/!(dist)/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  # Renovate security update: storybook@9.1.17
  - storybook@9.1.17
