packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**/!(dist)/**'
  - 'demos/**/!(dist)/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  # Renovate security update: pnpm@10.28.2
  - pnpm@10.28.2
