packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**/!(dist)/**'
  - 'demos/**/!(dist)/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

minimumReleaseAge: 1209600 #14 days
