packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**/!(dist)/**'
  - 'demos/**/!(dist)/**'
  # exclude packages that are inside test directories
  - '!**/test/**'

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  # Renovate security update: esbuild@0.28.1
  - esbuild@0.28.1
