import { fetchStyleComponents } from './styles-helper';
import { setCustomElementsManifest } from '@storybook/web-components';

export default async function loadCustomElements() {
  await fetch('./custom-elements.json');

  // Use dynamic manifest generated by Vite on runtime
  const response = await fetch('./custom-elements.json');
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const customElements = await response.json();

  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
  const stylesAreAlreadyIncluded = customElements.modules.some((module: { styles: boolean }) => module.styles);
  if (!stylesAreAlreadyIncluded) {
    const styleComponents = await fetchStyleComponents();
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
    customElements.modules = [...customElements.modules, ...styleComponents];
  }

  setCustomElementsManifest(customElements);
  console.log('Custom elements manifest loaded');
}
