export default {
  base: [
    { name: 'animate-bounce-once', value: 'bounce-once var(--sd-duration-medium, 300ms) ease-in-out;' },
    { name: 'animate-grow', value: 'grow linear;' },
    { name: 'animate-loader-current', value: 'wave 1.3s infinite, loader-color-current 2.6s infinite;' },
    { name: 'animate-loader-primary', value: 'wave 1.3s infinite, loader-color-primary 2.6s infinite;' },
    { name: 'animate-loader-white', value: 'wave 1.3s infinite, loader-color-white 2.6s infinite;' },
    { name: 'aspect-16/10', value: 'var(--sd-aspect-16\\/10);' },
    { name: 'aspect-21/9', value: 'var(--sd-aspect-21\\/9);' },
    { name: 'aspect-2/1', value: 'var(--sd-aspect-2\\/1);' },
    { name: 'aspect-3/2', value: 'var(--sd-aspect-3\\/2);' },
    { name: 'aspect-3/4', value: 'var(--sd-aspect-3\\/4);' },
    { name: 'aspect-4/3', value: 'var(--sd-aspect-4\\/3);' },
    { name: 'aspect-4/5', value: 'var(--sd-aspect-4\\/5);' },
    { name: 'aspect-5/4', value: 'var(--sd-aspect-5\\/4);' },
    { name: 'aspect-6/5', value: 'var(--sd-aspect-6\\/5);' },
    { name: 'aspect-golden-ratio', value: 'var(--sd-aspect-golden-ratio);' },
    { name: 'aspect-square', value: 'var(--sd-aspect-square);' },
    { name: 'aspect-video', value: 'var(--sd-aspect-video);' },
    { name: 'background-color-accent-300', value: 'rgba(var(--sd-color-background-accent-300));' },
    { name: 'background-color-accent-500', value: 'rgba(var(--sd-color-background-accent-500));' },
    { name: 'background-color-accent-550', value: 'rgba(var(--sd-color-background-accent-550));' },
    { name: 'background-color-accent-700', value: 'rgba(var(--sd-color-background-accent-700));' },
    { name: 'background-color-accent', value: 'rgba(var(--sd-color-background-accent));' },
    { name: 'background-color-error-400', value: 'rgba(var(--sd-color-background-error-400));' },
    { name: 'background-color-error', value: 'rgba(var(--sd-color-background-error));' },
    { name: 'background-color-info', value: 'rgba(var(--sd-color-background-info));' },
    { name: 'background-color-neutral-100', value: 'rgba(var(--sd-color-background-neutral-100));' },
    { name: 'background-color-neutral-200', value: 'rgba(var(--sd-color-background-neutral-200));' },
    { name: 'background-color-neutral-300', value: 'rgba(var(--sd-color-background-neutral-300));' },
    { name: 'background-color-neutral-400', value: 'rgba(var(--sd-color-background-neutral-400));' },
    { name: 'background-color-neutral-500', value: 'rgba(var(--sd-color-background-neutral-500));' },
    { name: 'background-color-neutral-600', value: 'rgba(var(--sd-color-background-neutral-600));' },
    { name: 'background-color-neutral-800', value: 'rgba(var(--sd-color-background-neutral-800));' },
    { name: 'background-color-primary-100', value: 'rgba(var(--sd-color-background-primary-100));' },
    { name: 'background-color-primary-200', value: 'rgba(var(--sd-color-background-primary-200));' },
    { name: 'background-color-primary-300', value: 'rgba(var(--sd-color-background-primary-300));' },
    { name: 'background-color-primary-500', value: 'rgba(var(--sd-color-background-primary-500));' },
    { name: 'background-color-primary-800', value: 'rgba(var(--sd-color-background-primary-800));' },
    { name: 'background-color-primary', value: 'rgba(var(--sd-color-background-primary));' },
    { name: 'background-color-success', value: 'rgba(var(--sd-color-background-success));' },
    { name: 'background-color-warning', value: 'rgba(var(--sd-color-background-warning));' },
    { name: 'background-color-white', value: 'rgba(var(--sd-color-background-white));' },
    { name: 'border-color-accent-550', value: 'rgba(var(--sd-color-border-accent-550));' },
    { name: 'border-color-accent', value: 'rgba(var(--sd-color-border-accent));' },
    { name: 'border-color-error-400', value: 'rgba(var(--sd-color-border-error-400));' },
    { name: 'border-color-error', value: 'rgba(var(--sd-color-border-error));' },
    { name: 'border-color-neutral-400', value: 'rgba(var(--sd-color-border-neutral-400));' },
    { name: 'border-color-neutral-500', value: 'rgba(var(--sd-color-border-neutral-500));' },
    { name: 'border-color-neutral-600', value: 'rgba(var(--sd-color-border-neutral-600));' },
    { name: 'border-color-neutral-800', value: 'rgba(var(--sd-color-border-neutral-800));' },
    { name: 'border-color-primary-100', value: 'rgba(var(--sd-color-border-primary-100));' },
    { name: 'border-color-primary-200', value: 'rgba(var(--sd-color-border-primary-200));' },
    { name: 'border-color-primary-400', value: 'rgba(var(--sd-color-border-primary-400));' },
    { name: 'border-color-primary-500', value: 'rgba(var(--sd-color-border-primary-500));' },
    { name: 'border-color-primary-800', value: 'rgba(var(--sd-color-border-primary-800));' },
    { name: 'border-color-primary', value: 'rgba(var(--sd-color-border-primary));' },
    { name: 'border-color-success', value: 'rgba(var(--sd-color-border-success));' },
    { name: 'border-color-white', value: 'rgba(var(--sd-color-border-white));' },
    { name: 'border-width-2', value: 'var(--sd-border-width-2);' },
    { name: 'border-width-4', value: 'var(--sd-border-width-4);' },
    { name: 'border-width-6', value: 'var(--sd-border-width-6);' },
    { name: 'border-width-default', value: 'var(--sd-border-width);' },
    { name: 'drop-shadow-listbox', value: 'var(--sd-drop-shadow-listbox);' },
    { name: 'drop-shadow-sm', value: 'var(--sd-drop-shadow-sm);' },
    { name: 'drop-shadow-xs', value: 'var(--sd-drop-shadow-xs);' },
    { name: 'drop-shadow', value: 'var(--sd-drop-shadow);' },
    { name: 'fill-accent-550', value: 'rgba(var(--sd-color-icon-fill-accent-550));' },
    { name: 'fill-accent', value: 'rgba(var(--sd-color-icon-fill-accent));' },
    { name: 'fill-error-400', value: 'rgba(var(--sd-color-icon-fill-error-400));' },
    { name: 'fill-error', value: 'rgba(var(--sd-color-icon-fill-error));' },
    { name: 'fill-neutral-400', value: 'rgba(var(--sd-color-icon-fill-neutral-400));' },
    { name: 'fill-neutral-500', value: 'rgba(var(--sd-color-icon-fill-neutral-500));' },
    { name: 'fill-neutral-600', value: 'rgba(var(--sd-color-icon-fill-neutral-600));' },
    { name: 'fill-neutral-800', value: 'rgba(var(--sd-color-icon-fill-neutral-800));' },
    { name: 'fill-primary-100', value: 'rgba(var(--sd-color-icon-fill-primary-100));' },
    { name: 'fill-primary-200', value: 'rgba(var(--sd-color-icon-fill-primary-200));' },
    { name: 'fill-primary-400', value: 'rgba(var(--sd-color-icon-fill-primary-400));' },
    { name: 'fill-primary-500', value: 'rgba(var(--sd-color-icon-fill-primary-500));' },
    { name: 'fill-primary-800', value: 'rgba(var(--sd-color-icon-fill-primary-800));' },
    { name: 'fill-primary', value: 'rgba(var(--sd-color-icon-fill-primary));' },
    { name: 'fill-risk-high', value: 'rgba(var(--sd-color-icon-fill-risk-high));' },
    { name: 'fill-risk-increased', value: 'rgba(var(--sd-color-icon-fill-risk-increased));' },
    { name: 'fill-risk-low', value: 'rgba(var(--sd-color-icon-fill-risk-low));' },
    { name: 'fill-risk-moderate', value: 'rgba(var(--sd-color-icon-fill-risk-moderate));' },
    { name: 'fill-risk-veryhigh', value: 'rgba(var(--sd-color-icon-fill-risk-veryhigh));' },
    { name: 'fill-success', value: 'rgba(var(--sd-color-icon-fill-success));' },
    { name: 'fill-white', value: 'rgba(var(--sd-color-icon-fill-white));' },
    { name: 'font-primary', value: 'var(--sd-font-primary);' },
    { name: 'font-weight-bold', value: 'var(--sd-font-weight-bold);' },
    { name: 'font-weight-normal', value: 'var(--sd-font-weight-normal);' },
    { name: 'opacity-0', value: 'var(--sd-opacity-0);' },
    { name: 'opacity-100', value: 'var(--sd-opacity-100);' },
    { name: 'opacity-10', value: 'var(--sd-opacity-10);' },
    { name: 'opacity-20', value: 'var(--sd-opacity-20);' },
    { name: 'opacity-30', value: 'var(--sd-opacity-30);' },
    { name: 'opacity-50', value: 'var(--sd-opacity-50);' },
    { name: 'opacity-55', value: 'var(--sd-opacity-55);' },
    { name: 'opacity-5', value: 'var(--sd-opacity-5);' },
    { name: 'opacity-60', value: 'var(--sd-opacity-60);' },
    { name: 'opacity-70', value: 'var(--sd-opacity-70);' },
    { name: 'opacity-75', value: 'var(--sd-opacity-75);' },
    { name: 'opacity-80', value: 'var(--sd-opacity-80);' },
    { name: 'opacity-85', value: 'var(--sd-opacity-85);' },
    { name: 'opacity-90', value: 'var(--sd-opacity-90);' },
    { name: 'outline-color-error', value: 'var(--sd-color-border-error, var(--sd-color-error));' },
    { name: 'outline-color-primary', value: 'var(--sd-color-border-primary, var(--sd-color-primary));' },
    { name: 'radius-default', value: 'var(--sd-radius);' },
    { name: 'radius-full', value: 'var(--sd-radius-full);' },
    { name: 'radius-lg', value: 'var(--sd-radius-lg);' },
    { name: 'radius-md', value: 'var(--sd-radius-md);' },
    { name: 'radius-none', value: 'var(--sd-radius-none);' },
    { name: 'radius-sm', value: 'var(--sd-radius-sm);' },
    { name: 'shadow-listbox', value: 'var(--sd-shadow-listbox);' },
    { name: 'shadow-sm', value: 'var(--sd-shadow-sm);' },
    { name: 'shadow-xs', value: 'var(--sd-shadow-xs);' },
    { name: 'shadow', value: 'var(--sd-shadow);' },
    { name: 'sizing-0', value: 'var(--sd-sizing-0);' },
    { name: 'sizing-0.25', value: 'var(--sd-sizing-0\\.25);' },
    { name: 'sizing-0.5', value: 'var(--sd-sizing-0\\.5);' },
    { name: 'sizing-10', value: 'var(--sd-sizing-10);' },
    { name: 'sizing-12', value: 'var(--sd-sizing-12);' },
    { name: 'sizing-16', value: 'var(--sd-sizing-16);' },
    { name: 'sizing-1', value: 'var(--sd-sizing-1);' },
    { name: 'sizing-20', value: 'var(--sd-sizing-20);' },
    { name: 'sizing-24', value: 'var(--sd-sizing-24);' },
    { name: 'sizing-2', value: 'var(--sd-sizing-2);' },
    { name: 'sizing-2.5', value: 'var(--sd-sizing-2\\.5);' },
    { name: 'sizing-3', value: 'var(--sd-sizing-3);' },
    { name: 'sizing-4', value: 'var(--sd-sizing-4);' },
    { name: 'sizing-5', value: 'var(--sd-sizing-5);' },
    { name: 'sizing-6', value: 'var(--sd-sizing-6);' },
    { name: 'sizing-8', value: 'var(--sd-sizing-8);' },
    { name: 'sizing-varspacing', value: 'var(--tw-varspacing);' },
    { name: 'spacing-0.25', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'spacing-0.5', value: 'var(--sd-spacing-0\\.5);' },
    { name: 'spacing-10', value: 'var(--sd-spacing-10);' },
    { name: 'spacing-12', value: 'var(--sd-spacing-12);' },
    { name: 'spacing-14', value: 'var(--sd-spacing-14);' },
    { name: 'spacing-16', value: 'var(--sd-spacing-16);' },
    { name: 'spacing-1', value: 'var(--sd-spacing-1);' },
    { name: 'spacing-1.5', value: 'var(--sd-spacing-1\\.5);' },
    { name: 'spacing-20', value: 'var(--sd-spacing-20);' },
    { name: 'spacing-24', value: 'var(--sd-spacing-24);' },
    { name: 'spacing-2', value: 'var(--sd-spacing-2);' },
    { name: 'spacing-2.5', value: 'var(--sd-spacing-2\\.5);' },
    { name: 'spacing-32', value: 'var(--sd-spacing-32);' },
    { name: 'spacing-3', value: 'var(--sd-spacing-3);' },
    { name: 'spacing-40', value: 'var(--sd-spacing-40);' },
    { name: 'spacing-4', value: 'var(--sd-spacing-4);' },
    { name: 'spacing-6', value: 'var(--sd-spacing-6);' },
    { name: 'spacing-8', value: 'var(--sd-spacing-8);' },
    { name: 'spacing-varspacing', value: 'var(--tw-varspacing);' },
    { name: 'spacing', value: 'var(--sd-spacing-1);' },
    { name: 'text-2xl', value: 'var(--sd-text-2xl);' },
    { name: 'text-3xl', value: 'var(--sd-text-3xl);' },
    { name: 'text-4xl', value: 'var(--sd-text-4xl);' },
    { name: 'text-base', value: 'var(--sd-text-base);' },
    { name: 'text-color-accent', value: 'rgba(var(--sd-color-text-accent));' },
    { name: 'text-color-black', value: 'rgba(var(--sd-color-text-black));' },
    { name: 'text-color-error', value: 'rgba(var(--sd-color-text-error));' },
    { name: 'text-color-neutral-500', value: 'rgba(var(--sd-color-text-neutral-500));' },
    { name: 'text-color-neutral-600', value: 'rgba(var(--sd-color-text-neutral-600));' },
    { name: 'text-color-neutral-700', value: 'rgba(var(--sd-color-text-neutral-700));' },
    { name: 'text-color-primary-100', value: 'rgba(var(--sd-color-text-primary-100));' },
    { name: 'text-color-primary-200', value: 'rgba(var(--sd-color-text-primary-200));' },
    { name: 'text-color-primary-400', value: 'rgba(var(--sd-color-text-primary-400));' },
    { name: 'text-color-primary-500', value: 'rgba(var(--sd-color-text-primary-500));' },
    { name: 'text-color-primary-800', value: 'rgba(var(--sd-color-text-primary-800));' },
    { name: 'text-color-primary', value: 'rgba(var(--sd-color-text-primary));' },
    { name: 'text-color-success', value: 'rgba(var(--sd-color-text-success));' },
    { name: 'text-color-white', value: 'rgba(var(--sd-color-text-white));' },
    { name: 'text-lg', value: 'var(--sd-text-lg);' },
    { name: 'text-sm', value: 'var(--sd-text-sm);' },
    { name: 'text-xl', value: 'var(--sd-text-xl);' },
    { name: 'text-xs', value: 'var(--sd-text-xs);' },
    { name: 'transition-duration-fast', value: 'var(--sd-duration-fast, 150ms);' },
    { name: 'transition-duration-medium', value: 'var(--sd-duration-medium, 300ms);' },
    { name: 'transition-duration-slow', value: 'var(--sd-duration-slow, 500ms);' },
    { name: 'transition-duration-x-slow', value: 'var(--sd-duration-x-slow, 750ms);' }
  ],
  utilities: [
    { name: 'z-10', declarations: [{ prop: 'z-index', value: '10' }] },
    { name: 'z-20', declarations: [{ prop: 'z-index', value: '20' }] },
    { name: 'z-30', declarations: [{ prop: 'z-index', value: '30' }] },
    { name: 'z-40', declarations: [{ prop: 'z-index', value: '40' }] },
    { name: 'z-50', declarations: [{ prop: 'z-index', value: '50' }] },
    { name: 'z-alert-group', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-alert-group, 950)' }] },
    { name: 'z-auto', declarations: [{ prop: 'z-index', value: 'auto' }] },
    { name: 'z-dialog', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-dialog, 800)' }] },
    { name: 'z-drawer', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-drawer, 700)' }] },
    { name: 'z-dropdown', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-dropdown, 900)' }] },
    { name: 'z-header', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-header, 600)' }] },
    { name: 'z-tooltip', declarations: [{ prop: 'z-index', value: 'var(--sd-z-index-tooltip, 1000)' }] },
    { name: 'varspacing-*', declarations: [{ prop: '--tw-varspacing', value: '--value(--spacing-*)' }] },
    {
      name: 'focus-outline',
      declarations: [
        { prop: 'outline-style', value: 'solid' },
        { prop: 'outline-offset', value: '2px' },
        { prop: 'outline-width', value: '2px' },
        { prop: 'outline-color', value: 'rgba(var(--outline-color-primary))' }
      ]
    },
    {
      name: 'focus-outline-inverted',
      declarations: [
        { prop: 'outline-style', value: 'solid' },
        { prop: 'outline-offset', value: '2px' },
        { prop: 'outline-width', value: '2px' },
        { prop: 'outline-color', value: 'rgba(var(--outline-color-white))' }
      ]
    }
  ],
  theme: [
    { name: 'sd-theme', value: "'ui-light';" },
    { name: 'sd-accordion-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-accordion-color-icon-fill', value: 'var(--sd-color-primary);' },
    { name: 'sd-accordion-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-accordion-padding-block', value: 'var(--sd-spacing-3);' },
    { name: 'sd-accordion__indicator-color', value: 'var(--sd-color-accent);' },
    { name: 'sd-aspect-16/10', value: '16 / 10;' },
    { name: 'sd-aspect-21/9', value: '21 / 9;' },
    { name: 'sd-aspect-2/1', value: '2 / 1;' },
    { name: 'sd-aspect-3/2', value: '3 / 2;' },
    { name: 'sd-aspect-3/4', value: '3 / 4;' },
    { name: 'sd-aspect-4/3', value: '4 / 3;' },
    { name: 'sd-aspect-4/5', value: '4 / 5;' },
    { name: 'sd-aspect-5/4', value: '5 / 4;' },
    { name: 'sd-aspect-6/5', value: '6 / 5;' },
    { name: 'sd-aspect-golden-ratio', value: '1.6180339887498948482 / 1;' },
    { name: 'sd-aspect-square', value: '1 / 1;' },
    { name: 'sd-aspect-video', value: '16 / 9;' },
    { name: 'sd-audio__slide-bar--inverted-color-background', value: 'var(--sd-color-primary-400);' },
    { name: 'sd-audio__track-bar--inverted-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-badge--blue--inverted-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-badge--blue--inverted-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-badge--blue-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-badge--green-color--inverted-background', value: 'var(--sd-color-success);' },
    { name: 'sd-badge--green-color--inverted-text', value: 'var(--sd-color-white);' },
    { name: 'sd-badge--green-color-background', value: 'var(--sd-color-success);' },
    { name: 'sd-badge--inverted-color-border', value: 'var(--sd-color-primary);' },
    { name: 'sd-badge--red--inverted-background', value: 'var(--sd-color-error);' },
    { name: 'sd-badge--red--inverted-text', value: 'var(--sd-color-white);' },
    { name: 'sd-badge--red-color-background', value: 'var(--sd-color-error);' },
    { name: 'sd-border-width-2', value: '0.125rem;' },
    { name: 'sd-border-width-4', value: '0.25rem;' },
    { name: 'sd-border-width-6', value: '0.375rem;' },
    { name: 'sd-border-width', value: '0.0625rem;' },
    { name: 'sd-brandshape--neutral-100-color-background', value: 'var(--sd-color-neutral-100);' },
    { name: 'sd-brandshape--white-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-breadcrumb__separator--current-color', value: 'var(--sd-color-accent);' },
    { name: 'sd-breadcrumb__separator-color', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-button--cta--inverted--active-color-background', value: 'var(--sd-color-accent-700);' },
    { name: 'sd-button--cta--inverted--active-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button--cta--inverted--default-color-background', value: 'var(--sd-color-accent);' },
    { name: 'sd-button--cta--inverted--default-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button--cta--inverted--hover-color-background', value: 'var(--sd-color-accent-500);' },
    { name: 'sd-button--cta--inverted--hover-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button--inverted--disabled-color-background', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-button--inverted--disabled-color-border', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-button--inverted--disabled-color-text', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-button--primary--active-color-text', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--primary--default-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-button--primary--default-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button--primary--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-button--primary--hover-color-text', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--primary--inverted--active-color-background', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--primary--inverted--active-color-text', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-button--primary--inverted--default-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-button--primary--inverted--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-button--primary--inverted--hover-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--primary--inverted--hover-color-text', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-button--secondary--active-color-background', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--secondary--active-color-text', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-button--secondary--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-button--secondary--disabled-color-text', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-button--secondary--hover-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--secondary--inverted--active-color-background', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-button--secondary--inverted--active-color-text', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--secondary--inverted--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-button--secondary--inverted--hover-color-text', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--secondary--inverted-color-border', value: 'var(--sd-color-white);' },
    { name: 'sd-button--secondary--inverted-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button--secondary--size-lg-padding-block', value: '0.6875rem;' },
    { name: 'sd-button--secondary--size-md-padding-block', value: '0.4375rem;' },
    { name: 'sd-button--secondary--size-sm-padding-block', value: '0.28125rem;' },
    { name: 'sd-button--secondary-padding-inline', value: '0.9375rem;' },
    { name: 'sd-button--size-lg-font-size', value: 'var(--sd-spacing-4);' },
    { name: 'sd-button--size-lg-icon-height', value: 'var(--sd-spacing-6);' },
    { name: 'sd-button--size-lg-min-height', value: 'var(--sd-spacing-12);' },
    { name: 'sd-button--size-lg-padding-block', value: 'var(--sd-spacing-3);' },
    { name: 'sd-button--size-md--icon-only-padding-inline', value: 'var(--sd-spacing-2\\.5);' },
    { name: 'sd-button--size-md-border-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-button--size-md-font-size', value: 'var(--sd-spacing-4);' },
    { name: 'sd-button--size-md-min-height', value: 'var(--sd-spacing-10);' },
    { name: 'sd-button--size-md-padding-block', value: 'var(--sd-spacing-2);' },
    { name: 'sd-button--size-sm-border-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-button--size-sm-font-size', value: '0.875rem;' },
    { name: 'sd-button--size-sm-padding-block', value: '0.34375rem;' },
    { name: 'sd-button--tertiary--active-color-background', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--tertiary--active-color-text', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-button--tertiary--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-button--tertiary--disabled-color-text', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-button--tertiary--hover-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--tertiary--inverted--active-color-background', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-button--tertiary--inverted--active-color-text', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-button--tertiary--inverted--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-button--tertiary--inverted--hover-color-text', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-button--tertiary--inverted-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-button-border-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-button-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-button-font-weight', value: 'var(--sd-font-weight-normal);' },
    { name: 'sd-button-padding-inline', value: 'var(--sd-spacing-4);' },
    { name: 'sd-carousel--active--inverted-color-border', value: 'var(--sd-color-accent);' },
    { name: 'sd-carousel--active-color-border', value: 'var(--sd-color-accent);' },
    { name: 'sd-carousel__pager-dot--inverted--hovered-background', value: 'var(--sd-color-accent);' },
    { name: 'sd-carousel__pager-dot--inverted-background', value: 'var(--sd-color-accent);' },
    { name: 'sd-carousel__pager-dot--inverted-border', value: 'var(--sd-color-white);' },
    { name: 'sd-carousel__pager-dot-background', value: 'var(--sd-color-accent);' },
    { name: 'sd-carousel__pager-dot-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-checkbox-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-chip--primary-200-color-background', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-chip--primary-200-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-chip--primary-300-color-background', value: 'var(--sd-color-primary-300);' },
    { name: 'sd-chip--primary-300-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-chip--primary-500-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-chip--primary-500-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-chip--primary-500-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-chip--white-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-chip--white-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-chip-border-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-choice-control-font-weight', value: 'var(--sd-font-weight-normal);' },
    { name: 'sd-color-accent-100', value: '182 223 170;' },
    { name: 'sd-color-accent-200', value: '142 208 130;' },
    { name: 'sd-color-accent-300', value: '108 194 84;' },
    { name: 'sd-color-accent-400', value: '45 157 0;' },
    { name: 'sd-color-accent-500', value: '37 136 14;' },
    { name: 'sd-color-accent-550', value: '54 123 40;' },
    { name: 'sd-color-accent-600', value: '49 111 36;' },
    { name: 'sd-color-accent-700', value: '33 87 37;' },
    { name: 'sd-color-accent-800', value: '25 65 27;' },
    { name: 'sd-color-accent', value: '45 157 0;' },
    { name: 'sd-color-background-accent-300', value: 'var(--sd-color-accent-300);' },
    { name: 'sd-color-background-accent-500', value: 'var(--sd-color-accent-500);' },
    { name: 'sd-color-background-accent-550', value: 'var(--sd-color-success);' },
    { name: 'sd-color-background-accent-700', value: 'var(--sd-color-accent-700);' },
    { name: 'sd-color-background-accent', value: 'var(--sd-color-accent);' },
    { name: 'sd-color-background-error-400', value: 'var(--sd-color-error-400);' },
    { name: 'sd-color-background-error', value: 'var(--sd-color-error);' },
    { name: 'sd-color-background-info', value: 'var(--sd-color-info);' },
    { name: 'sd-color-background-neutral-100', value: 'var(--sd-color-neutral-100);' },
    { name: 'sd-color-background-neutral-200', value: 'var(--sd-color-neutral-200);' },
    { name: 'sd-color-background-neutral-300', value: 'var(--sd-color-neutral-300);' },
    { name: 'sd-color-background-neutral-400', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-color-background-neutral-500', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-color-background-neutral-600', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-color-background-neutral-800', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-color-background-primary-100', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-color-background-primary-200', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-color-background-primary-300', value: 'var(--sd-color-primary-300);' },
    { name: 'sd-color-background-primary-500', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-color-background-primary-800', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-color-background-primary', value: 'var(--sd-color-primary);' },
    { name: 'sd-color-background-success', value: 'var(--sd-color-success);' },
    { name: 'sd-color-background-warning', value: 'var(--sd-color-warning);' },
    { name: 'sd-color-background-white', value: 'var(--sd-color-white);' },
    { name: 'sd-color-black', value: '24 24 24;' },
    { name: 'sd-color-border-accent-550', value: 'var(--sd-color-success);' },
    { name: 'sd-color-border-accent', value: 'var(--sd-color-accent);' },
    { name: 'sd-color-border-error-400', value: 'var(--sd-color-error-400);' },
    { name: 'sd-color-border-error', value: 'var(--sd-color-error);' },
    { name: 'sd-color-border-neutral-400', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-color-border-neutral-500', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-color-border-neutral-600', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-color-border-neutral-800', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-color-border-primary-100', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-color-border-primary-200', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-color-border-primary-400', value: 'var(--sd-color-primary-400);' },
    { name: 'sd-color-border-primary-500', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-color-border-primary-800', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-color-border-primary', value: 'var(--sd-color-primary);' },
    { name: 'sd-color-border-success', value: 'var(--sd-color-success);' },
    { name: 'sd-color-border-white', value: 'var(--sd-color-white);' },
    { name: 'sd-color-error-250', value: '234 88 107;' },
    { name: 'sd-color-error-300', value: '204 25 55;' },
    { name: 'sd-color-error-400', value: '172 25 56;' },
    { name: 'sd-color-error-500', value: '125 20 45;' },
    { name: 'sd-color-error', value: '204 25 55;' },
    { name: 'sd-color-icon-fill-accent-550', value: 'var(--sd-color-success);' },
    { name: 'sd-color-icon-fill-accent', value: 'var(--sd-color-accent);' },
    { name: 'sd-color-icon-fill-error-400', value: 'var(--sd-color-error-400);' },
    { name: 'sd-color-icon-fill-error', value: 'var(--sd-color-error);' },
    { name: 'sd-color-icon-fill-neutral-400', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-color-icon-fill-neutral-500', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-color-icon-fill-neutral-600', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-color-icon-fill-neutral-800', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-color-icon-fill-primary-100', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-color-icon-fill-primary-200', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-color-icon-fill-primary-400', value: 'var(--sd-color-primary-400);' },
    { name: 'sd-color-icon-fill-primary-500', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-color-icon-fill-primary-800', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-color-icon-fill-primary', value: 'var(--sd-color-primary);' },
    { name: 'sd-color-icon-fill-risk-high', value: 'var(--sd-color-risk-high);' },
    { name: 'sd-color-icon-fill-risk-increased', value: 'var(--sd-color-risk-increased);' },
    { name: 'sd-color-icon-fill-risk-low', value: 'var(--sd-color-risk-low);' },
    { name: 'sd-color-icon-fill-risk-moderate', value: 'var(--sd-color-risk-moderate);' },
    { name: 'sd-color-icon-fill-risk-veryhigh', value: 'var(--sd-color-risk-veryhigh);' },
    { name: 'sd-color-icon-fill-success', value: 'var(--sd-color-success);' },
    { name: 'sd-color-icon-fill-white', value: 'var(--sd-color-white);' },
    { name: 'sd-color-info', value: '21 130 213;' },
    { name: 'sd-color-neutral-100', value: '246 246 246;' },
    { name: 'sd-color-neutral-200', value: '233 233 233;' },
    { name: 'sd-color-neutral-300', value: '218 218 218;' },
    { name: 'sd-color-neutral-400', value: '195 195 195;' },
    { name: 'sd-color-neutral-500', value: '174 174 174;' },
    { name: 'sd-color-neutral-600', value: '136 136 136;' },
    { name: 'sd-color-neutral-700', value: '104 104 104;' },
    { name: 'sd-color-neutral-800', value: '81 81 81;' },
    { name: 'sd-color-primary-100', value: '236 240 249;' },
    { name: 'sd-color-primary-200', value: '224 233 243;' },
    { name: 'sd-color-primary-300', value: '200 213 231;' },
    { name: 'sd-color-primary-400', value: '153 171 208;' },
    { name: 'sd-color-primary-500', value: '70 109 175;' },
    { name: 'sd-color-primary-600', value: '0 53 142;' },
    { name: 'sd-color-primary-700', value: '19 46 110;' },
    { name: 'sd-color-primary-750', value: '10 32 74;' },
    { name: 'sd-color-primary-800', value: '5 21 48;' },
    { name: 'sd-color-primary-900', value: '2 9 32;' },
    { name: 'sd-color-primary', value: '0 53 142;' },
    { name: 'sd-color-risk-high', value: '250 155 30;' },
    { name: 'sd-color-risk-increased', value: '255 240 0;' },
    { name: 'sd-color-risk-low', value: '1 125 195;' },
    { name: 'sd-color-risk-moderate', value: '0 165 147;' },
    { name: 'sd-color-risk-veryhigh', value: '255 0 0;' },
    { name: 'sd-color-success', value: '54 123 40;' },
    { name: 'sd-color-text-accent', value: 'var(--sd-color-accent);' },
    { name: 'sd-color-text-black', value: 'var(--sd-color-black);' },
    { name: 'sd-color-text-error', value: 'var(--sd-color-error);' },
    { name: 'sd-color-text-neutral-500', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-color-text-neutral-600', value: 'var(--sd-color-neutral-600);' },
    { name: 'sd-color-text-neutral-700', value: 'var(--sd-color-neutral-700);' },
    { name: 'sd-color-text-primary-100', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-color-text-primary-200', value: 'var(--sd-color-primary-200);' },
    { name: 'sd-color-text-primary-400', value: 'var(--sd-color-primary-400);' },
    { name: 'sd-color-text-primary-500', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-color-text-primary-800', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-color-text-primary', value: 'var(--sd-color-primary);' },
    { name: 'sd-color-text-success', value: 'var(--sd-color-success);' },
    { name: 'sd-color-text-white', value: 'var(--sd-color-white);' },
    { name: 'sd-color-warning', value: '187 141 32;' },
    { name: 'sd-color-white', value: '255 255 255;' },
    { name: 'sd-combobox__tag-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-datepicker__date-item--current-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-datepicker__date-item--current-font-weight', value: 'var(--sd-font-weight-bold);' },
    { name: 'sd-datepicker__date-item--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-datepicker__date-item--hover--default-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-datepicker__date-item--hover--default-color-border', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-datepicker__date-item--hover--default-color-text', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-datepicker__date-item--hover--prev-next-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-datepicker__date-item--hover--prev-next-color-text', value: 'var(--sd-color-neutral-700);' },
    { name: 'sd-datepicker__date-item--range-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-datepicker__date-item--selected--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-datepicker__date-item--selected-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-datepicker__date-item--selected-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-divider--inverted-color-border', value: 'var(--sd-color-primary-400);' },
    { name: 'sd-drop-shadow-listbox', value: '0px 1px 3px rgba(81, 81, 81, 0.75);' },
    { name: 'sd-drop-shadow-sm', value: '0.5px 0.5px 1.5px #515151;' },
    { name: 'sd-drop-shadow-xs', value: '0.5px 0.5px 1.5px #515151;' },
    { name: 'sd-drop-shadow', value: '0px 1px 3px rgba(81, 81, 81, 0.75);' },
    { name: 'sd-dropdown-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-duration-fast', value: '150ms;' },
    { name: 'sd-duration-medium', value: '300ms;' },
    { name: 'sd-duration-slow', value: '500ms;' },
    { name: 'sd-duration-x-slow', value: '750ms;' },
    { name: 'sd-flag--neutral-200-color-background', value: 'var(--sd-color-neutral-200);' },
    { name: 'sd-flag--neutral-200-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-flag--neutral-300-color-background', value: 'var(--sd-color-neutral-300);' },
    { name: 'sd-flag--neutral-300-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-flag--neutral-500-color-background', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-flag--neutral-500-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-flag--white-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-flag--white-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-flag-border-radius', value: '0;' },
    { name: 'sd-font-primary', value: "'Frutiger Neue';" },
    { name: 'sd-font-weight-bold', value: '600;' },
    { name: 'sd-font-weight-normal', value: '400;' },
    { name: 'sd-footnotes--target--inverted-color-background', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-form-control--filled__floating-label-color-text', value: 'var(--sd-color-neutral-700);' },
    { name: 'sd-form-control--invalid-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-form-control-border-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-form-control-color-border', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-form-control-color-text', value: 'var(--sd-color-black);' },
    { name: 'sd-form-control__listbox-border-bottom-left-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-form-control__listbox-border-bottom-right-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-form-control__listbox-border-top-left-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-form-control__listbox-border-top-right-radius', value: 'var(--sd-spacing-1);' },
    { name: 'sd-header-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-header-padding-bottom', value: '0;' },
    { name: 'sd-header__shadow-height', value: 'var(--sd-spacing-1);' },
    { name: 'sd-header__underline-color-background', value: '255 255 255 / 0;' },
    { name: 'sd-header__underline-height', value: 'var(--sd-spacing-2);' },
    { name: 'sd-headline--3xl-onwards-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-informational-gradient--primary-800-color-background', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-informational-gradient--white-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-interactive--active-color-text', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-interactive--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-link-color--hover-icon', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-link-color--none-icon', value: 'var(--sd-color-primary);' },
    { name: 'sd-link-color--pressed-icon', value: 'var(--sd-color-primary-800);' },
    { name: 'sd-map-marker--cluster--default-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-map-marker--cluster--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-map-marker--cluster-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-map-marker--main-color-background', value: 'var(--sd-color-accent-500);' },
    { name: 'sd-map-marker--pin--default-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-map-marker--pin--hover-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-map-marker--pin-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-marker-border-width', value: '0;' },
    { name: 'sd-marker-font-size', value: '0.875rem;' },
    { name: 'sd-marker-font-weight', value: 'var(--sd-font-weight-normal);' },
    { name: 'sd-menu-item--disabled-color-icon-fill', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-menu-item--disabled-color-text', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-menu-item-color-icon-fill', value: 'var(--sd-color-primary);' },
    { name: 'sd-menu-item-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-navigable-border-radius', value: '0;' },
    { name: 'sd-navigable-font-size', value: 'var(--sd-spacing-4);' },
    { name: 'sd-navigable__current-indicator-border-radius', value: '0;' },
    { name: 'sd-navigable__current-indicator-height', value: 'var(--sd-spacing-1);' },
    { name: 'sd-navigable__current-indicator-width', value: 'var(--sd-spacing-1);' },
    { name: 'sd-navigation-item-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-notification--error-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-notification--info-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-notification--success-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-notification--warning-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-notification-color-border', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-notification-color-icon-fill', value: 'var(--sd-color-primary);' },
    { name: 'sd-notification__duration-indicator-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-opacity-0', value: '0%;' },
    { name: 'sd-opacity-100', value: '100%;' },
    { name: 'sd-opacity-10', value: '10%;' },
    { name: 'sd-opacity-20', value: '20%;' },
    { name: 'sd-opacity-30', value: '30%;' },
    { name: 'sd-opacity-50', value: '50%;' },
    { name: 'sd-opacity-55', value: '55%;' },
    { name: 'sd-opacity-5', value: '5%;' },
    { name: 'sd-opacity-60', value: '60%;' },
    { name: 'sd-opacity-70', value: '70%;' },
    { name: 'sd-opacity-75', value: '75%;' },
    { name: 'sd-opacity-80', value: '80%;' },
    { name: 'sd-opacity-85', value: '85%;' },
    { name: 'sd-opacity-90', value: '90%;' },
    { name: 'sd-overlay-color-background', value: '5 21 48 / 0.9;' },
    { name: 'sd-pagination--default-border', value: 'var(--sd-color-accent);' },
    { name: 'sd-pagination--inverted-border', value: 'var(--sd-color-accent);' },
    { name: 'sd-panel-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-quickfact--expandable-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-radio--checked--default-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-radio--checked--default__icon-color-background', value: 'var(--sd-color-accent);' },
    { name: 'sd-radio--checked--hover-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-radio--checked--hover__icon-color-background', value: 'var(--sd-color-success);' },
    { name: 'sd-radio--checked--invalid--default-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-radio--checked--invalid--default__icon-color-background', value: 'var(--sd-color-error);' },
    { name: 'sd-radio--checked--invalid--hover__icon-color-background', value: 'var(--sd-color-error-400);' },
    { name: 'sd-radio--default--invalid-color-background', value: 'var(--sd-color-white);' },
    { name: 'sd-radio-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-radio-button--hover-color-background', value: '255 255 255 / 0;' },
    { name: 'sd-radio-button--hover-color-text', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-radio-button-border-radius', value: '624.9375rem;' },
    { name: 'sd-radio-button-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-radio-button-group-border-radius', value: '624.9375rem;' },
    { name: 'sd-radio-button-group-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-radio-button-group-padding', value: '0;' },
    { name: 'sd-radius-full', value: '624.9375rem;' },
    { name: 'sd-radius-lg', value: '0.5rem;' },
    { name: 'sd-radius-md', value: '0.375rem;' },
    { name: 'sd-radius-none', value: '0;' },
    { name: 'sd-radius-sm', value: '0.125rem;' },
    { name: 'sd-radius', value: '0.25rem;' },
    { name: 'sd-range-scale-ticks-color-text', value: 'var(--sd-color-black);' },
    { name: 'sd-range__bar-border-width', value: 'var(--sd-spacing-1);' },
    { name: 'sd-shadow-listbox', value: '0px 1px 3px 0px rgba(81, 81, 81, 0.75);' },
    { name: 'sd-shadow-sm', value: '0.5px 0.5px 1.5px 0px #515151;' },
    { name: 'sd-shadow-xs', value: '0.5px 0.5px 1.5px 0px #515151;' },
    { name: 'sd-shadow', value: '0px 1px 3px 0px rgba(81, 81, 81, 0.75);' },
    { name: 'sd-sizing-0', value: '0;' },
    { name: 'sd-sizing-0.25', value: '0.0625rem;' },
    { name: 'sd-sizing-0.5', value: '0.125rem;' },
    { name: 'sd-sizing-10', value: '2.5rem;' },
    { name: 'sd-sizing-12', value: '3rem;' },
    { name: 'sd-sizing-16', value: '4rem;' },
    { name: 'sd-sizing-1', value: '0.25rem;' },
    { name: 'sd-sizing-20', value: '5rem;' },
    { name: 'sd-sizing-24', value: '6rem;' },
    { name: 'sd-sizing-2', value: '0.5rem;' },
    { name: 'sd-sizing-2.5', value: '0.625rem;' },
    { name: 'sd-sizing-3', value: '0.75rem;' },
    { name: 'sd-sizing-4', value: '1rem;' },
    { name: 'sd-sizing-5', value: '1.25rem;' },
    { name: 'sd-sizing-6', value: '1.5rem;' },
    { name: 'sd-sizing-8', value: '2rem;' },
    { name: 'sd-skeleton-color', value: 'var(--sd-color-neutral-200);' },
    { name: 'sd-spacing-0.25', value: '0.0625rem;' },
    { name: 'sd-spacing-0.5', value: '0.125rem;' },
    { name: 'sd-spacing-10', value: '2.5rem;' },
    { name: 'sd-spacing-12', value: '3rem;' },
    { name: 'sd-spacing-14', value: '3.5rem;' },
    { name: 'sd-spacing-16', value: '4rem;' },
    { name: 'sd-spacing-1', value: '0.25rem;' },
    { name: 'sd-spacing-1.5', value: '0.375rem;' },
    { name: 'sd-spacing-20', value: '5rem;' },
    { name: 'sd-spacing-24', value: '6rem;' },
    { name: 'sd-spacing-2', value: '0.5rem;' },
    { name: 'sd-spacing-2.5', value: '0.625rem;' },
    { name: 'sd-spacing-32', value: '8rem;' },
    { name: 'sd-spacing-3', value: '0.75rem;' },
    { name: 'sd-spacing-40', value: '10rem;' },
    { name: 'sd-spacing-4', value: '1rem;' },
    { name: 'sd-spacing-6', value: '1.5rem;' },
    { name: 'sd-spacing-8', value: '2rem;' },
    { name: 'sd-step-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-step__circle-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-step__tail-border-width', value: 'var(--sd-spacing-0\\.25);' },
    { name: 'sd-switch--checked--hover-color-background', value: 'var(--sd-color-success);' },
    { name: 'sd-switch--unchecked-color-border', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-switch--unchecked__icon-color-background', value: 'var(--sd-color-neutral-800);' },
    { name: 'sd-switch-color-text', value: 'var(--sd-color-black);' },
    { name: 'sd-tab--active-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-tab--hover-color-background', value: 'var(--sd-color-neutral-200);' },
    { name: 'sd-tab-color-border', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-tab-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-tag--default--hover-color-background', value: '255 255 255 / 0;' },
    { name: 'sd-tag--default-color-background', value: '255 255 255 / 0;' },
    { name: 'sd-tag--default-color-border', value: 'var(--sd-color-primary);' },
    { name: 'sd-tag--default-color-text', value: 'var(--sd-color-primary);' },
    { name: 'sd-tag--disabled-color-text', value: 'var(--sd-color-neutral-500);' },
    { name: 'sd-tag--selected--default-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-tag--selected--default-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-tag--selected--default-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-tag--selected--hover-color-background', value: 'var(--sd-color-primary-500);' },
    { name: 'sd-tag--selected--hover-color-border', value: '255 255 255 / 0;' },
    { name: 'sd-tag--selected--hover-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-tag--selected-border-width', value: '0;' },
    { name: 'sd-tag--size-lg-font-size', value: 'var(--sd-spacing-4);' },
    { name: 'sd-tag--size-sm-font-size', value: '0.875rem;' },
    { name: 'sd-tag-border-radius', value: '624.9375rem;' },
    { name: 'sd-tag-font-weight', value: 'var(--sd-font-weight-normal);' },
    { name: 'sd-teaser--neutral-100-color-background', value: 'var(--sd-color-neutral-100);' },
    { name: 'sd-teaser--neutral-400-color-border', value: 'var(--sd-color-neutral-400);' },
    { name: 'sd-teaser--primary-100-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-teaser-border-radius', value: '0;' },
    { name: 'sd-teaser-media--neutral-100--hover-color-background', value: 'var(--sd-color-neutral-100);' },
    { name: 'sd-teaser-media--neutral-100-color-background', value: 'var(--sd-color-neutral-100);' },
    { name: 'sd-teaser-media--primary-100--hover-color-background', value: 'var(--sd-color-primary-100);' },
    { name: 'sd-teaser-media--primary-100-color-background', value: '236 240 249 / 0.8;' },
    { name: 'sd-teaser-media--white--hover-color-background', value: '255 255 255 / 0.9;' },
    { name: 'sd-teaser-media--white-color-background', value: '255 255 255 / 0.8;' },
    { name: 'sd-text-2xl', value: '1.75rem;' },
    { name: 'sd-text-3xl', value: '2rem;' },
    { name: 'sd-text-4xl', value: '2.5rem;' },
    { name: 'sd-text-base', value: '1rem;' },
    { name: 'sd-text-lg', value: '1.25rem;' },
    { name: 'sd-text-sm', value: '0.875rem;' },
    { name: 'sd-text-xl', value: '1.5rem;' },
    { name: 'sd-text-xs', value: '0.75rem;' },
    { name: 'sd-tooltip-color-background', value: 'var(--sd-color-primary);' },
    { name: 'sd-tooltip-color-text', value: 'var(--sd-color-white);' },
    { name: 'sd-video--play-button-color-background', value: '255 255 255 / 0.8;' },
    { name: 'sd-video--play-button-color-icon-fill', value: 'var(--sd-color-primary);' }
  ]
};
