import { setCustomElementsManifest } from '@storybook/web-components';
import 'normalize.css';

async function loadCustomElements() {
  let customElements;

  fetch('/custom-elements.json')
    .then(() => {
      // Use dynamic manifest generated by Vite on runtime
      return fetch('/custom-elements.json').then(res => res.json());
    })
    .catch(() => {
      console.log('Failed to fetch custom-elements.json. Using local manifest...');
      // Use manifest file generated on build time
      return import('../dist/custom-elements.json');
    })
    .then(customElements => {
      setCustomElementsManifest(customElements);
    });

  setCustomElementsManifest(customElements);
  console.log('Custom elements manifest set', customElements);
}

loadCustomElements();
